import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import prisma from "@/lib/prisma";

// GET - List children for the hospital
export async function GET() {
  try {
    const session = await auth();
    if (!session?.user || session.user.role !== "HOSPITAL_ADMIN") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const hospitalAdmin = await prisma.hospitalAdmin.findFirst({
      where: { userId: session.user.id },
      select: { hospitalId: true },
    });

    if (!hospitalAdmin) {
      return NextResponse.json({ error: "Hospital not found" }, { status: 404 });
    }

    const children = await prisma.child.findMany({
      where: { currentHospitalId: hospitalAdmin.hospitalId },
      include: {
        mother: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            phone: true,
          },
        },
        _count: {
          select: {
            immunizationRecords: true,
            immunizationSchedules: true,
          },
        },
      },
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json(children);
  } catch (error) {
    console.error("Error fetching children:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

// POST - Register a new child
export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user || session.user.role !== "HOSPITAL_ADMIN") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const hospitalAdmin = await prisma.hospitalAdmin.findFirst({
      where: { userId: session.user.id },
      select: { hospitalId: true },
    });

    if (!hospitalAdmin) {
      return NextResponse.json({ error: "Hospital not found" }, { status: 404 });
    }

    const body = await request.json();
    const {
      motherId,
      firstName,
      lastName,
      dateOfBirth,
      gender,
      birthWeight,
      bloodGroup,
      genotype,
      allergies,
    } = body;

    // Verify mother belongs to this hospital
    const mother = await prisma.mother.findFirst({
      where: {
        id: motherId,
        currentHospitalId: hospitalAdmin.hospitalId,
      },
    });

    if (!mother) {
      return NextResponse.json({ error: "Mother not found" }, { status: 404 });
    }

    // Create child and auto-generate immunization schedules
    const child = await prisma.$transaction(async (tx) => {
      // Create the child
      const newChild = await tx.child.create({
        data: {
          motherId,
          currentHospitalId: hospitalAdmin.hospitalId,
          registeredById: session.user.id,
          firstName,
          lastName,
          dateOfBirth: new Date(dateOfBirth),
          gender,
          birthWeight: birthWeight || null,
          bloodGroup: bloodGroup || null,
          genotype: genotype || null,
          allergies: allergies || null,
        },
        include: {
          mother: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              phone: true,
            },
          },
        },
      });

      // Get active vaccines for the hospital to auto-generate schedules
      const vaccines = await tx.hospitalVaccine.findMany({
        where: {
          hospitalId: hospitalAdmin.hospitalId,
          isActive: true,
        },
        include: {
          versions: {
            orderBy: { versionNumber: "desc" },
            take: 1,
          },
        },
      });

      // Generate immunization schedules based on vaccines
      const dob = new Date(dateOfBirth);
      const schedules = [];

      for (const vaccine of vaccines) {
        const currentVersion = vaccine.versions[0];
        
        for (let dose = 1; dose <= vaccine.dosesRequired; dose++) {
          // Calculate scheduled date based on min age and dose interval
          let weeksFromBirth = vaccine.minAgeWeeks;
          if (dose > 1 && vaccine.intervalWeeks) {
            weeksFromBirth += (dose - 1) * vaccine.intervalWeeks;
          }

          const scheduledDate = new Date(dob);
          scheduledDate.setDate(scheduledDate.getDate() + weeksFromBirth * 7);

          schedules.push({
            childId: newChild.id,
            vaccineId: vaccine.id,
            vaccineVersionId: currentVersion?.id || null,
            doseNumber: dose,
            scheduledDate,
            status: scheduledDate < new Date() ? "OVERDUE" as const : "SCHEDULED" as const,
            autoGenerated: true,
          });
        }
      }

      if (schedules.length > 0) {
        await tx.immunizationSchedule.createMany({
          data: schedules,
        });
      }

      return newChild;
    });

    return NextResponse.json(child, { status: 201 });
  } catch (error) {
    console.error("Error creating child:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
